//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anket()
        {
            this.Para = new HashSet<Para>();
        }
    
        public int ID_anket { get; set; }
        public int ID_mened { get; set; }
        public int ID_test_astrol { get; set; }
        public int ID_test_psixo { get; set; }
        public int ID_client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Mened Mened { get; set; }
        public virtual Test_astrol Test_astrol { get; set; }
        public virtual Test_psixo Test_psixo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Para> Para { get; set; }
    }
}
