//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Anket = new HashSet<Anket>();
        }
    
        public int ID_clienta { get; set; }
        public string Familiy { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public byte ID_Pol { get; set; }
        public byte Vozrast { get; set; }
        public short Ves { get; set; }
        public string Znak_zodiaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anket> Anket { get; set; }
        public virtual Pol Pol { get; set; }
    }
}
